### ISSUE TITLE
Unsupported uri-js

### ISSUE THREAD

**Issue by kibertoad** [criteria-labs/criteria-api-tools#21]
Hey!
Your library is using uri-js, which hasn't received updates in three years.

Would you be interested in a PR that would switch to an up-to-date fork toad-uri-js, which addresses https://github.com/garycourt/uri-js/issues/96 and https://github.com/garycourt/uri-js/issues/87, several transitive security issues with dependencies, and aims to address https://github.com/garycourt/uri-js/issues/92?

**Comment by jamesmoschou** [comment]
Hey @kibertoad go for it!

**Comment by kibertoad** [comment]
@jamesmoschou Done!

**Comment by jamesmoschou** [comment]
@kibertoad Thanks! released as:

@criteria/json-schema@0.9.1
@criteria/json-schema-validation@0.9.2
